In [6]:
import torch
import torch.nn as nn

# Define the input dimensions
in_channels = 3
out_channels = 16
kernel_size = 3
stride = 1
padding = 1

# Create an instance of nn.Conv2d
conv = nn.Conv2d(in_channels, out_channels, kernel_size, stride, padding)

# Create a dummy input tensor
x = torch.randn(1, in_channels, 64, 64)
print(x.shape)
# Pass the input through the convolutional layer
output = conv(x)
print(x.shape)

print(output.shape)


torch.Size([1, 3, 64, 64])
torch.Size([1, 3, 64, 64])
torch.Size([1, 16, 64, 64])


In [4]:
# Accessing the weights (kernels) of the convolutional layer
kernels = conv.weight.data

print(kernels.shape)  # Shape of the kernels

# Printing the first kernel
print(kernels[0])  # Accessing the first kernel

# Printing the second kernel
print(kernels[1])  # Accessing the second kernel

# Printing all the kernels
for i in range(out_channels):
    print(kernels[i])  # Accessing each kernel in the convolutional layer

# Printing the biases of the convolutional layer
biases = conv.bias.data
print(biases)

torch.Size([16, 3, 3, 3])
tensor([[[-0.1402, -0.1655,  0.1324],
         [ 0.1140,  0.0094, -0.0528],
         [ 0.1668,  0.0306,  0.1692]],

        [[-0.0660,  0.1239, -0.0586],
         [ 0.0457,  0.0062,  0.0013],
         [-0.0378, -0.0123,  0.1427]],

        [[-0.1043,  0.1368, -0.1188],
         [ 0.1799, -0.1521, -0.1501],
         [ 0.1436,  0.1564, -0.0587]]])
tensor([[[ 0.0501, -0.0615, -0.1638],
         [ 0.1437,  0.1462, -0.1147],
         [ 0.0364,  0.0617,  0.0272]],

        [[ 0.1655, -0.1463,  0.0043],
         [ 0.0156, -0.1301,  0.0996],
         [ 0.1344, -0.0267,  0.0201]],

        [[ 0.0575,  0.0696,  0.0355],
         [ 0.1709, -0.1154,  0.0448],
         [-0.1769,  0.0091, -0.0553]]])
tensor([[[-0.1402, -0.1655,  0.1324],
         [ 0.1140,  0.0094, -0.0528],
         [ 0.1668,  0.0306,  0.1692]],

        [[-0.0660,  0.1239, -0.0586],
         [ 0.0457,  0.0062,  0.0013],
         [-0.0378, -0.0123,  0.1427]],

        [[-0.1043,  0.1368, -0.1188],
        