In [2]:
import torch
import numpy as np

In [3]:
import torch.nn as nn

In [4]:
from torchvision import datasets,models,transforms

In [5]:
import torch.nn.functional as F

In [6]:
torch.tensor([1,2,3,4,5,6])

tensor([1, 2, 3, 4, 5, 6])

In [12]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [8]:
#Numpy Array
np_array = np.array(data)

#Tensor from numpy array
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [9]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n",x_ones.dtype)

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 
 torch.int64


In [10]:
x_ones = torch.ones_like(x_data,dtype=torch.float) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n",x_ones.dtype)

Ones Tensor: 
 tensor([[1., 1.],
        [1., 1.]]) 
 torch.float32


In [11]:
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.8510, 0.3293],
        [0.2183, 0.2747]]) 



In [12]:
shape = (4,6)
rand_tensor  = torch.rand(shape)
ones_tensor  = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.1030, 0.4605, 0.0430, 0.6301, 0.5493, 0.3666],
        [0.4153, 0.2150, 0.2148, 0.8284, 0.3531, 0.3517],
        [0.0841, 0.2163, 0.8238, 0.0812, 0.9937, 0.0509],
        [0.2098, 0.1309, 0.7317, 0.6709, 0.9947, 0.6256]]) 

Ones Tensor: 
 tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])


In [8]:
tnsr = torch.rand((3,4))
print(tnsr)
print(f"Shape of tensor: {tnsr.shape}")
print(f"Datatype of tensor: {tnsr.dtype}")
print(f"Device tensor is stored on: {tnsr.device}")

tensor([[0.5819, 0.5859, 0.9563, 0.0111],
        [0.6844, 0.0829, 0.3759, 0.2246],
        [0.9509, 0.6869, 0.7374, 0.7155]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [9]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor_ = tnsr.to("cuda")
else:
    tensor_ = tnsr.to("cpu")
print(tensor_)

tensor([[0.5819, 0.5859, 0.9563, 0.0111],
        [0.6844, 0.0829, 0.3759, 0.2246],
        [0.9509, 0.6869, 0.7374, 0.7155]], device='cuda:0')


In [11]:
tensor_ [:,1]

tensor([0.5859, 0.0829, 0.6869], device='cuda:0')

In [12]:
tensor_ [:,-1]

tensor([0.0111, 0.2246, 0.7155], device='cuda:0')

In [14]:
tensor_ [0:3,0:2]

tensor([[0.5819, 0.5859],
        [0.6844, 0.0829],
        [0.9509, 0.6869]], device='cuda:0')

In [15]:
tensor_ [...,-1]

tensor([0.0111, 0.2246, 0.7155], device='cuda:0')

In [16]:
tensor1 = torch.rand((3,4))
tensor2 = torch.rand((3,4))
torch.cat([tensor1,tensor2],dim=0)

tensor([[0.9418, 0.5388, 0.2038, 0.3453],
        [0.2787, 0.2072, 0.8368, 0.4930],
        [0.9088, 0.2931, 0.2100, 0.9787],
        [0.8773, 0.1006, 0.4071, 0.4906],
        [0.4179, 0.1646, 0.7078, 0.3374],
        [0.5606, 0.8347, 0.5564, 0.6056]])

In [20]:
y1 = tnsr @ tnsr.T
print(y1)
y2 = tnsr.matmul(tnsr.T)
print(y2)

tensor([[1.5965, 0.8088, 1.6689],
        [0.8088, 0.6670, 1.1457],
        [1.6689, 1.1457, 2.4317]])
tensor([[1.5965, 0.8088, 1.6689],
        [0.8088, 0.6670, 1.1457],
        [1.6689, 1.1457, 2.4317]])


In [26]:
x1 = torch.tensor([[2,2],[2,2]])
x2 = torch.tensor([[3,3],[3,3]]).T
print(x1 @ x2)
print(x1.matmul(x2) )

tensor([[12, 12],
        [12, 12]])
tensor([[12, 12],
        [12, 12]])


In [32]:
torch.tensordot(x1,x1)

tensor(16)

In [33]:
torch.tensordot(x2,x2)

tensor(36)

In [18]:
tensor_.sum()

tensor(6.5938, device='cuda:0')

In [19]:
tensor_.sum().item()


6.5937604904174805