In [13]:
import torch.nn as nn
import torch
# input dimensions
nz = 6
ngf = 20
# define the ConvTranspose2d layer
conv_transpose = nn.ConvTranspose2d(nz, ngf, 4, 4, 0, bias=False)
# constant kernel tensor for demonstration purposes
kernel_data = torch.Tensor([[
                                [[1, 2],[3, 4]], 
                                [[5, 6],[7, 8]]
                           ]])
conv_transpose.weight.data = kernel_data
 
# constant input tensor for demonstration purposes
input_data = torch.Tensor([[[1.0], [2.0]]])
input_tensor = input_data.unsqueeze(0)  # add batch dimension

# pass constant input tensor through ConvTranspose2d layer with constant kernel
output_tensor = conv_transpose(input_tensor)

# print the kernel tensor
print("================================================")
print("Kernel tensor shape:", kernel_data.shape)
print(kernel_data)
print("================================================")

# print the input tensor
print("Input tensor shape:", input_tensor.shape)
print("===>input_tensor ", input_tensor)
print("================================================")

# print the output tensor
print("Output tensor shape:", output_tensor.shape)
print(output_tensor)
print("================================================")

Kernel tensor shape: torch.Size([1, 2, 2, 2])
tensor([[[[1., 2.],
          [3., 4.]],

         [[5., 6.],
          [7., 8.]]]])
Input tensor shape: torch.Size([1, 1, 2, 1])
===>input_tensor  tensor([[[[1.],
          [2.]]]])
Output tensor shape: torch.Size([1, 2, 6, 2])
tensor([[[[ 1.,  2.],
          [ 3.,  4.],
          [ 0.,  0.],
          [ 0.,  0.],
          [ 2.,  4.],
          [ 6.,  8.]],

         [[ 5.,  6.],
          [ 7.,  8.],
          [ 0.,  0.],
          [ 0.,  0.],
          [10., 12.],
          [14., 16.]]]], grad_fn=<SlowConvTranspose2DBackward0>)


In [35]:
import torch.nn as nn
import torch
# input dimensions
nz  = 2
ngf = 2

# define the ConvTranspose2d layer
conv_transpose = nn.ConvTranspose2d(nz, ngf, 4, 1, 0, bias=False)
# access the weight attribute of the ConvTranspose2d layer
kernel = conv_transpose.weight

# print the kernel tensor
print("================================================")
print("Kernel tensor shape:", kernel.shape)
print(kernel)
print("================================================")
# generate random input tensor
input_tensor = torch.randn(1, nz, 1, 1)
print("Input tensor shape:", input_tensor.shape)
print("===>input_tensor ",input_tensor)
print("================================================")
# pass input tensor through ConvTranspose2d layer
output_tensor = conv_transpose(input_tensor)
print("Output tensor shape:", output_tensor.shape)
print(output_tensor)
print("================================================")


Kernel tensor shape: torch.Size([2, 2, 4, 4])
Parameter containing:
tensor([[[[ 0.0315,  0.0060,  0.1732, -0.1499],
          [ 0.1646,  0.1038, -0.1158, -0.0574],
          [-0.1735,  0.0779, -0.0977, -0.1230],
          [ 0.0813, -0.0590,  0.0395, -0.1450]],

         [[ 0.1407,  0.0616, -0.0357,  0.1150],
          [ 0.1498, -0.0175, -0.0855, -0.0572],
          [ 0.0917,  0.1078, -0.1499,  0.0574],
          [-0.0147,  0.0440,  0.0600, -0.1575]]],


        [[[ 0.0949, -0.1288,  0.0553,  0.0942],
          [-0.1761,  0.0628, -0.0968,  0.0440],
          [ 0.1738,  0.0794, -0.1198, -0.1310],
          [-0.1731,  0.1638,  0.0438, -0.1382]],

         [[-0.1366,  0.0721,  0.1212,  0.0304],
          [-0.1731, -0.0165,  0.1715, -0.1532],
          [ 0.0228, -0.0083,  0.0433,  0.0228],
          [ 0.1691, -0.0458,  0.0308,  0.1205]]]], requires_grad=True)
Input tensor shape: torch.Size([1, 2, 1, 1])
===>input_tensor  tensor([[[[-0.2945]],

         [[ 0.1041]]]])
Output tensor shape: to

In [25]:
import torch

#Creating a tensor filled with a specific value
size = (3, 4)
value = 5
tensor = torch.full(size, value)

print(tensor)

tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]])
